`timescale 1ns / 1ps

//Verilog generated by VPR 8.0.0+unkown from post-place-and-route implementation
/*module core (
    input \clk ,
    input \reset ,
    output \out[0] ,
    output \out[1] ,
    output \out[2] ,
    output \out[3] ,
    output \out[4] ,
    output \out[5] ,
    output \out[6] ,
    output \out[7] 
);
*/

module test();

reg clk, reset;
wire [7:0] out;

core uut (clk,reset,out[0],out[1],out[2],out[3],out[4],out[5],out[6],out[7]);

//initial $sdf_annotate("/home/nanditha/Dropbox/vsd/fpga-vsd-slides/Day3/post_synth_files/up_counter_post_synthesis.sdf", uut);


initial
begin
    clk = 1'b0;
    reset = 1'b0;
    
    #10;
    reset = 1'b1;
    #50;
    reset = 1'b0;
end

always #5 clk = ~clk;
initial #200 $finish;

endmodule
